BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]

    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(string? SearchString = null) //Method that make a list of items and shows on the Index page
        {
            List<Company> CompanysList = _unitOfWork.Company.GetAll().ToList();
            return View(CompanysList);
        }

        [HttpPost]
        public IActionResult Refresh()
        {
            List<Company> CompanysList = _unitOfWork.Company.GetAll(includeProperties: "Category").ToList();

            return RedirectToAction("Index", CompanysList);
        }
        public IActionResult CreateOrUpdate(int? id) //Method that shows the page
        {
            //Creating CompanyVM so we can pass several parameters from different classes.

            if (id == null || id == 0)
            {
                return View(new Company());
            }
            else
            {
                Company company = _unitOfWork.Company.Get(p => p.Id == id);
                return View(company);
            }
        }

        [HttpPost] //Method that shows the page
        public IActionResult CreateOrUpdate(Company company)
        {
            if (company.Id == 0)
            {
                _unitOfWork.Company.Add(company);
                _unitOfWork.Save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                _unitOfWork.Company.Update(company);
                _unitOfWork.Save();
                TempData["success"] = "Company updated successfully";
                return RedirectToAction("Index");
            }

        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var CompanyFromDb = _unitOfWork.Company.Get(p => p.Id == id);

            if (CompanyFromDb != null)
            {
                _unitOfWork.Company.Remove(CompanyFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Company deleted successfully";

                return Json(new { success = true, message = "Company deleted successfully" });

            }
            else
            {
                return View(CompanyFromDb);

            }
        }

        #region API Calls
        [HttpGet]
        public ActionResult GetAll()
        {
            List<Company> Companys = _unitOfWork.Company.GetAll().ToList();
            return Json(new { data = Companys });
        }

        #endregion
    }
}

BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Ultility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using System.Collections;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index(string? SearchString = null) //Method that make a list of items and shows on the Index page
        {
            List<Product> productsList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();



            if (!string.IsNullOrEmpty(SearchString))
            {
                bool hasFound = false;

                productsList.Clear();

                foreach (var item in _unitOfWork.Product.GetAll())
                {
                    if (item.Title!.ToLower().Contains(SearchString.ToLower()))
                    {
                        var result = _unitOfWork.Product.GetAll().Where(s => s.Title!.ToLower().Contains(SearchString.ToLower()));

                        productsList.AddRange(result);
                        hasFound = true;


                    }
                    else if (item.Author!.ToLower().Contains(SearchString.ToLower()))
                    {
                        var result = _unitOfWork.Product.GetAll().Where(s => s.Author!.ToLower().Contains(SearchString.ToLower()));

                        productsList.AddRange(result);
                        hasFound = true;

                    }
                    else if (item.Category!.Name!.ToLower().Contains(SearchString.ToLower()))
                    {
                        var result = _unitOfWork.Product.GetAll().Where(s => s.Category!.Name!.ToLower().Contains(SearchString.ToLower()));

                        productsList.AddRange(result);
                        hasFound = true;


                    }
                    else if (item.ISBN!.ToLower().Contains(SearchString.ToLower()))
                    {
                        var result = _unitOfWork.Product.GetAll().Where(s => s.ISBN!.ToLower().Contains(SearchString.ToLower()));

                        productsList.AddRange(result);
                        hasFound = true;

                    }
                    else if (item.Id.ToString().ToLower()!.Contains(SearchString.ToLower()))
                    {
                        var result = _unitOfWork.Product.GetAll().Where(s => s.Id!.ToString().ToLower().Contains(SearchString.ToLower()));

                        productsList.AddRange(result);
                        hasFound = true;

                    }

                }
                if (hasFound)
                {
                    List<Product> tempList = [.. productsList];

                    productsList.Clear();

                    productsList = tempList.DistinctBy(s => s.Title).ToList();

                    return View(productsList);
                }
                else if (hasFound == false)
                {
                    TempData["error"] = "Not found";
                    return RedirectToAction("Index");
                }
            }

            return View(productsList);
        }

        [HttpPost]
        public IActionResult Refresh()
        {
            List<Product> productsList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return RedirectToAction("Index", productsList);
        }
        public IActionResult CreateOrUpdate(int? id) //Method that shows the page
        {
            //Creating ProductVM so we can pass several parameters from different classes.
            ProductVM productVM = new ProductVM
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(
                u => new SelectListItem { Text = u.Name, Value = u.Id.ToString() }),
                Product = new Product()
            };
            if (id == null || id == 0)
            {
                return View(productVM);
            }
            else
            {
                productVM.Product = _unitOfWork.Product.Get(p => p.Id == id);
                return View(productVM);
            }
        }

        [HttpPost] //Method that shows the page
        public IActionResult CreateOrUpdate(ProductVM productVM, IFormFile? file) //IFormFile needs to be if using one page for Create and Update.
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productPath = Path.Combine(wwwRootPath, @"images\product");

                if (!string.IsNullOrEmpty(productVM.Product.ImageURL))
                {
                    var oldImgPath = Path.Combine(wwwRootPath, productVM.Product.ImageURL.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImgPath))
                    {
                        System.IO.File.Delete(oldImgPath);
                    }
                }

                using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);

                }
                productVM.Product.ImageURL = @"\images\product\" + fileName;

                if (productVM.Product.Id == 0 && ModelState.IsValid)
                {
                    productVM.Product.Description = string.Empty;
                    _unitOfWork.Product.Add(productVM.Product);
                    _unitOfWork.Save();
                    TempData["success"] = "Category created successfully";
                    return RedirectToAction("Index");
                }
                else if (ModelState.IsValid)
                {
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                    TempData["success"] = "Category updated successfully";
                    return RedirectToAction("Index");
                }
                return View(productVM);


            }
            else
            {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(
                u => new SelectListItem { Text = u.Name, Value = u.Id.ToString() });


                if (productVM.Product.Id == 0 && ModelState.IsValid)
                {
                    productVM.Product.Description = string.Empty;
                    _unitOfWork.Product.Add(productVM.Product);
                    _unitOfWork.Save();
                    TempData["success"] = "Category created successfully";
                    return RedirectToAction("Index");
                }
                else if (ModelState.IsValid)
                {
                    if (productVM.Product.Description == null)
                    {
                        productVM.Product.Description = string.Empty;
                    }
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                    TempData["success"] = "Category updated successfully";
                    return RedirectToAction("Index");
                }
                return View(productVM);

            }

        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var productFromDb = _unitOfWork.Product.Get(p => p.Id == id);

            if (productFromDb != null)
            {
                _unitOfWork.Product.Remove(productFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Category deleted successfully";

                return Json(new { success = true, message = "Product deleted successfully" });

            }
            else
            {
                return View(productFromDb);

            }
        }

        #region API Calls
        [HttpGet]
        public ActionResult GetAll()
        {
            List<Product> products = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = products });
        }

        #endregion
    }
}

BulkyWeb/Areas/Customer/Controllers/CartController.cs
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.Customer.Controllers
{
    public class CartController : Controller
    {
        
         IUnitOfWork _unitOfWork { get; set; }
        ShoppingCartVM ShoppingCartVM { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [Area("customer"), Authorize]
        public IActionResult Index()
        {
            var getUserId = (ClaimsIdentity)User.Identity;

            
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ShoppingCartVM = new()
            {
                shoppingCarts  = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId,
                includeProperties: "Product"),
            };


                return View(ShoppingCartVM);
        }
    }
}

BulkyWeb/Controllers/CategoryController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers;


public class CategoryController : Controller
{
    private readonly ICategoryRepository _categoryRepo;
    public CategoryController(ICategoryRepository db)
    {
        _categoryRepo = db;

    }

    public IActionResult Index()
    {
        List<Category> objCategoryList = _categoryRepo.GetAll();

        return View(objCategoryList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Category obj)
    {


        if (obj.Name == obj.DisplayOrder.ToString()) ModelState.AddModelError("name", "Name and Order can not be the same.");

        ModelState.Remove("Id");
        if (obj != null && ModelState.IsValid) //ModelState.IsValid controlls if Category validation is valid.
        {
            _categoryRepo.Add(obj);
            _categoryRepo.Save();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index"); //return RedirectToAction("Index",Category); or other controller if needed.

        }
        return View();
    }


    public IActionResult Edit(int? id)
    {
        var categoryFromDb = _categoryRepo.Get(x=>x.Id==id);

        if (id == null || id == 0 || categoryFromDb == null)
        {
            return NotFound();
        }
        return View(categoryFromDb);
    }

    [HttpPost] // Important without it the page wont know what method to use => ERROR
    public IActionResult Edit(Category obj)
    {

        if (obj.Name == obj.DisplayOrder.ToString()) ModelState.AddModelError("name", "Name and Order can not be the same.");

        if (obj != null && ModelState.IsValid) //ModelState.IsValid controlls if Category validation is valid.
        {
            _categoryRepo.Update(obj);
            _categoryRepo.Save();
            TempData["success"] = "Category updated successfully";
            return RedirectToAction("Index"); //return RedirectToAction("Index",Category); or other controller if needed.

        }
        return View();
    }

    public IActionResult Delete(int? id)
    {
        var categoryFromDb = _categoryRepo.Get(c => c.Id == id);

        if (id == null || id == 0 || categoryFromDb == null)
        {
            return NotFound();
        }
        return View(categoryFromDb);
    }

    [HttpPost] // Important without it the page wont know what method to use => ERROR
    public IActionResult Delete(Category obj)
    {
        _categoryRepo.Remove(obj);
        _categoryRepo.Save();
        TempData["success"] = "Category deleted successfully";
        return RedirectToAction("Index"); //return RedirectToAction("Index",Category); or other controller if needed.
    }


}

BulkyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.6/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.IsInRole(SD.Role_Admin)) {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index"><i class="h6 bi bi-cart3"> ( 0 )</i></a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @*  <partial name="_Notifications" /> *@

        </main>
    </div>
    <div class="mt-5">
        <footer class="footer text-muted bg-primary text-center">
            <div class="container text-light">
                &copy; 2024 - BulkyBookWeb made with <i class="bi bi-heart-fill"></i>
            </div>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script> @*Sweet Alert*@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
 @*    <script src="//cdn.datatables.net/2.0.6/js/dataTables.min.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
 
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}